apiVersion: v1
kind: Pod
metadata:
  name: cirros-multinet
  annotations:
    switches: an-ovn-switch1
    k8s.v1.cni.cncf.io/networks: an-ovn-network1
spec:
  containers:
  - name: cirros
    image: cirros
    resources:
      limits:
        memory: "128Mi"
    command: ["sleep", "1000"]
