apiVersion: v1
kind: Pod
metadata:
  name: cirros-physnet
  annotations:
    switches: a-physnet-switch
    k8s.v1.cni.cncf.io/networks: an-ovn-physnet
spec:
  containers:
  - name: cirros
    image: cirros
    resources:
      limits:
        memory: "128Mi"
    command: ["sleep", "1000"]
